/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis.starships

import org.testng.Assert.assertNotNull
import org.testng.annotations.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
